apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      syslog:
        udp:
          listen_address: "0.0.0.0:54526"
        protocol: rfc3164
        location: UTC
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      loadbalancing:
        protocol:
          otlp:
        resolver:
          dns:
            hostname: otelcol.observability.svc.cluster.local

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [loadbalancing]
        logs:
          receivers: [syslog]
          processors: []
          exporters: [loadbalancing]