apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.crossplane.io/stable'
    targetRevision: 1.14.3
    chart: crossplane
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
