apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  destination:
    namespace: crossplane-system
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://charts.crossplane.io/stable'
      targetRevision: 1.14.3
      chart: crossplane
    - repoURL: 'https://github.com/edwindijkstrainmarsat/strimzi-demo.git'
      path: ./crossplane
      targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
