apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: sample-bucket-crossplane1
  annotations:
    project: "test-project"
  labels:
    app.kubernetes.io/instance: some-application
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: default