apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-cluster
spec:
  destination:
    name: ''
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    path: ./kafka/cluster
    repoURL: 'https://github.com/edwindijkstrainmarsat/strimzi-demo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false