apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 54.2.2
      chart: kube-prometheus-stack
      helm:
        values: |-
          prometheus:
            prometheusSpec:
              additionalScrapeConfigs:
                name: additional-scrape-configs
                key: prometheus-additional.yaml
        parameters:
          - name: prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues
            value: 'false'
          - name: prometheus.prometheusSpec.ignoreNamespaceSelectors
            value: 'true'
          - name: prometheus.prometheusSpec.probeSelectorNilUsesHelmValues
            value: 'false'
          - name: prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues
            value: 'false'
          - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
            value: 'false'
    - repoURL: 'https://github.com/edwindijkstrainmarsat/strimzi-demo.git'
      path: ./kafka/monitoring
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
