apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
spec:
  destination:
    name: ''
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://strimzi.io/charts/'
    path: ''
    targetRevision: 0.38.0
    chart: strimzi-kafka-operator
    helm:
      parameters:
        - name: dashboards.enabled
          value: 'true'
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
