apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-for-kafka
spec:
  destination:
    name: ''
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://provectus.github.io/kafka-ui-charts'
    targetRevision: 0.7.5
    chart: kafka-ui
    helm:
      values: |-
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: strimzi
                bootstrapServers: my-cluster-kafka-bootstrap:9092
                schemaRegistry: http://kafka-schema-ksqldb-cp-schema-registry:8081
          auth:
            type: disabled
          management:
            health:
              ldap:
                enabled: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions: []
